-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 21:09:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lk` DEFAULT CHARACTER SET utf8 ;
USE `lk` ;

-- -----------------------------------------------------
-- Table `lk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lk`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL,
  `FIO` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `password` VARCHAR(255) NOT NULL,
  `mailing` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lk`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lk`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lk`.`group_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lk`.`group_user` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `user_groups_idx` (`group_id` ASC) VISIBLE,
  INDEX `users_groups_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_group`
    FOREIGN KEY (`user_id`)
    REFERENCES `lk`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_user`
    FOREIGN KEY (`group_id`)
    REFERENCES `lk`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lk`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lk`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` CHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lk`.`message_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lk`.`message_sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `color_id` INT NOT NULL,
  `date_time_creation` DATETIME NOT NULL,
  `id_creator_user` INT NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `message_sections_users1_idx` (`id_creator_user` ASC) VISIBLE,
  INDEX `message_sections_message_sections1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `message_sections_color1_idx` (`color_id` ASC) VISIBLE,
  CONSTRAINT `message_sections_users1`
    FOREIGN KEY (`id_creator_user`)
    REFERENCES `lk`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `message_sections_message_sections1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `lk`.`message_sections` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `message_sections_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `lk`.`color` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lk`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lk`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `heading` VARCHAR(255) NULL,
  `date_time_creation` DATETIME NOT NULL,
  `id_sender` INT NOT NULL,
  `id_recipient` INT NOT NULL,
  `id_section` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `messages_users1_idx` (`id_sender` ASC) VISIBLE,
  INDEX `messages_users2_idx` (`id_recipient` ASC) VISIBLE,
  INDEX `message_sections1_idx` (`id_section` ASC) VISIBLE,
  CONSTRAINT `sender`
    FOREIGN KEY (`id_sender`)
    REFERENCES `lk`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `recipienr`
    FOREIGN KEY (`id_recipient`)
    REFERENCES `lk`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `section`
    FOREIGN KEY (`id_section`)
    REFERENCES `lk`.`message_sections` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
